
# Deploy on Gitlab Pages

# Define NODE as the type of image that docker will use, allowing use to access npm easily.

image: node

# Stage
pages:
  stage: deploy

  # No need to download dependencies every time pipeline runs
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
  # Restricting pipeline stage
  only:
    - master